version: "3"
services:
  web:
    build: .
    ports:
      - "80:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://db:27017/webapp
    depends_on:
      - db

  db:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
